<a href="https://colab.research.google.com/github/Jeesyuen/data-science-toolkit/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [1]:
import numpy as np

In [16]:
#numpy is like an array of number
a=np.array([1,2,3])
print(type(a), a.shape, a[1]) #type(a) → shows the data type of a, a.shape → shows the shape (or size) of the array,a[1] → gets the second element (since array indices start from 0)
a[0]=10 #reading or writing
print(a) #replace the first number (index 0) with 10

<class 'numpy.ndarray'> (3,) 2
[10  2  3]


In [4]:
b=np.array ([[1,2,3],[4,5,6]]) # 2 dimension (2 rows and 2 columns)
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
b=np.array ([[1,2,3],[4,5,6],[7,8,9]]) # 3 dimension (3 rows and 3 columns)
print(b)
print(b.shape) # show dimensional

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [8]:
print(b[0,0], b[1,1]) #refer dimensional table to find which row and which column to print the number you want

1 5


In [9]:
n1=np.zeros((2,2)) # np.zeros means creates an array filled with zeros
#numbers in the bracket means how many rows and how many columns (means 2 rows and 2 columns here)
print(n1) # the numbers printed out got decimal cause numpy use float

[[0. 0.]
 [0. 0.]]


In [10]:
n2=np.ones((1,2)) #np.ones means creates an array filled with 1 (same concept)
print(n2)

[[1. 1.]]


In [11]:
n3=np.full((2,2),7) #np.full() creates numpy array of a given shape and fills it with a specific value
#(2, 2) → means 2 rows and 2 columns, 7 → means every element will be filled with 7
print(n3)

[[7 7]
 [7 7]]


In [12]:
n4=np.eye(3) #np.eye() means to create an identity matrix
print(n4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
num4=np.random.random((2,2)) #creates random numbers between 0.0 and 1.0
print(num4)

[[0.59888911 0.22363061]
 [0.43909259 0.33702279]]


In [14]:
any_var=b[1,:]# back to slicing concept
print(any_var)# print second row (refer the 3x3 table)

[4 5 6]


In [15]:
any_var=b[1,:2] #only print 2nd row first and second numbers (refer to the slicing method)
print(any_var)

[4 5]
