<a href="https://colab.research.google.com/github/Jeesyuen/data-science-toolkit/blob/main/Tutorial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a numpy array of size 2 x 2

In [5]:
import numpy as np

In [10]:
a = np.array ([[1,1],[1,1]])
print(a)

[[1 1]
 [1 1]]


2. Create a random numpy array of size 3 x 4

In [11]:
b=np.random.random((3,4))
print(b)

[[0.89849674 0.05002723 0.97385877 0.72738792]
 [0.84391014 0.27152223 0.19021337 0.81351488]
 [0.21163479 0.89877465 0.20433742 0.0417669 ]]


3. Create a numpy array of ones and a numpy array of zeroes

In [12]:
c=np.ones((2,2))
print(c)

[[1. 1.]
 [1. 1.]]


In [14]:
d=np.zeros((2,2))
print(d)

[[0. 0.]
 [0. 0.]]


4. Create a random numpy array of size 6x3 and transpose it

In [16]:
e=np.random.random((6,3))
print(e)
print(e.T)

[[0.14068175 0.55166463 0.35938447]
 [0.99279598 0.94787183 0.85916799]
 [0.3237357  0.6962255  0.4064579 ]
 [0.52518089 0.52446923 0.09924451]
 [0.80730521 0.52102465 0.75219868]
 [0.28124404 0.94237207 0.487552  ]]
[[0.14068175 0.99279598 0.3237357  0.52518089 0.80730521 0.28124404]
 [0.55166463 0.94787183 0.6962255  0.52446923 0.52102465 0.94237207]
 [0.35938447 0.85916799 0.4064579  0.09924451 0.75219868 0.487552  ]]


5. Create two random numpy array of size n x p and p x m and then compute the dot product

In [20]:
f=np.random.randint(1,10,(3,3))
print(f)
g=np.random.randint(1,10,(3,4))
print(g)
product= np.dot(f,g)
print(product)

[[8 1 2]
 [9 7 1]
 [8 6 1]]
[[3 4 1 8]
 [9 2 6 1]
 [9 9 1 7]]
[[51 52 16 79]
 [99 59 52 86]
 [87 53 45 77]]
